#!/bin/bash

# If explicitly disabled, skip the hook
if [ "$(git config --get custom.hooks.commit-msg)" == "false" ]; then
  echo "commit-msg: hook disabled by user"
  exit 0
fi

pnpm exec commitlint --edit "$1"
