name: ci

on:
  workflow_dispatch: # allow manual trigger
  pull_request: # on pull request changes
  push:
    branches: [main] # on commits to the main branch

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to publish releases
      issues: write # to comment on released issues
      pull-requests: write # to comment on released PRs
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2.5.1
        with: { node-version: 20.x }
      - run: npm install -g pnpm@9
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test
      - run: pnpm run build
      # - run: pnpm run -r release
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
